os:
  - linux
  # - osx
  # - windows
language: rust
rust:
  - stable
  - beta
cache: cargo
jobs:
  allow_failures:
    - rust: beta
  fast_finish: true
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo build --verbose
  - cargo fmt --all --verbose -- --check
  - cargo clippy --verbose -- -D warnings
  - cargo test  --verbose
# https://docs.travis-ci.com/user/deployment/cargo/
# https://docs.travis-ci.com/user/deployment/releases/