language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo fmt --all --verbose -- --check
  - cargo clippy --verbose -- -D warnings
  - cargo test  --verbose